### ISSUE TITLE
automatic travis deployment fails (502 - Error uploading asset)

### ISSUE THREAD

**Issue by jakoch** [WPN-XM/WPN-XM#337]
the automatic travis deployment of assets fails.
only a few of the executables are uploaded, before a `502 - Error uploading asset (Octokit::BadGateway)` is hit.

- this is either a bug in the travis deployment.
- or a github limitation

possible workarounds:
- [ ] delete failed upload file and re-trigger the build
- [ ] use own "github_releases" tool and do the upload one by one with short delays
- [ ] use a travis build matrix
   - [ ] matrix for the 5 full installers php54-w32, php55-w32, php55-w64, php56-w32, php56-w64
   - [ ] additionally the 2 literc installers php56-w32, php56-w64
   - [ ] all in all: 7 matrix slots

```
Installing deploy dependencies

Fetching: addressable-2.3.7.gem (100%)
Successfully installed addressable-2.3.7
Fetching: multipart-post-2.0.0.gem (100%)
Successfully installed multipart-post-2.0.0
Fetching: faraday-0.9.1.gem (100%)
Successfully installed faraday-0.9.1
Fetching: sawyer-0.6.0.gem (100%)
Successfully installed sawyer-0.6.0
Fetching: octokit-3.8.0.gem (100%)
Successfully installed octokit-3.8.0
5 gems installed
Fetching: mime-types-2.4.3.gem (100%)
Successfully installed mime-types-2.4.3
1 gem installed
dpl.2

Preparing deploy

Logged in as Jens-André Koch
Deploying to repo: WPN-XM/WPN-XM
Current tag is: v0.8.1

dpl.3
Deploying application

/home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-3.8.0/lib/octokit/response/raise_error.rb:16:in `on_complete': POST https://uploads.github.com/repos/WPN-XM/WPN-XM/releases/1027211/assets?name=WPNXM-0.8.1-Standard-Setup-php56-w64.exe: 502 - Error uploading asset (Octokit::BadGateway)
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.1/lib/faraday/response.rb:9:in `block in call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.1/lib/faraday/response.rb:57:in `on_complete'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.1/lib/faraday/response.rb:8:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.1/lib/faraday/rack_builder.rb:139:in `build_response'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.1/lib/faraday/connection.rb:377:in `run_request'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/faraday-0.9.1/lib/faraday/connection.rb:177:in `post'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/sawyer-0.6.0/lib/sawyer/agent.rb:94:in `call'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-3.8.0/lib/octokit/client.rb:339:in `request'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/octokit-3.8.0/lib/octokit/client/releases.rb:94:in `upload_asset'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.9/lib/dpl/provider/releases.rb:118:in `block in push_app'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.9/lib/dpl/provider/releases.rb:102:in `each'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.9/lib/dpl/provider/releases.rb:102:in `push_app'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.9/lib/dpl/provider.rb:132:in `block in deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.9/lib/dpl/cli.rb:41:in `fold'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.9/lib/dpl/provider.rb:132:in `deploy'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.9/lib/dpl/cli.rb:32:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.9/lib/dpl/cli.rb:7:in `run'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/dpl-1.7.9/bin/dpl:5:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `load'
	from /home/travis/.rvm/gems/ruby-1.9.3-p551/bin/dpl:23:in `<main>'

failed to deploy
```

**Comment by jakoch** [comment]
**delete failed upload file and re-trigger the build**
